### PR TITLE
update mocha to 4

### PR DESCRIPTION
**Pull request by kellyselden**
closes #122

### CODE REVIEW

**Comment by rwjblue** [comment]
Do we have issues with this and apps that want to use ember-cli-mocha?  Specifically, ember-cli-mocha does not support Mocha 4.

@Turbo87 - Mind confirming if this is an issue or not?

**Comment by Turbo87** [comment]
This shouldn't matter as ember-cli-mocha brings in its own mocha dep

**Comment by Turbo87** [comment]
I'm surprised though that this PR is passing CI since https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/122 fails...

**Comment by kellyselden** [comment]
@Turbo87 approve and merge?

**Comment by Turbo87** [comment]
@kellyselden have you tried using Mocha 4 on any dependent projects? the main change was that it no longer stops the process automatically after tests have run, which makes it wait indefinitely for any running Promises. since https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/122 ran into that exact thing I'm a little worried that we're hitting that somewhere in the stack...

**Comment by kellyselden** [comment]
@Turbo87 I'm using mocha 4 in many projects without issue. I'm not using it with ember-cli-mocha though, only node-land tests.

**Comment by Turbo87** [comment]
That's all I needed to hear 😉

**Pull request merged**
