### PR TITLE
Use ember-cli v3.5.0-beta.1

### PR DESCRIPTION
**Pull request by dcyriller**
This PR aims at using a released version of ember-cli following https://github.com/ember-cli/ember-cli-blueprint-test-helpers/pull/153

May you provide a release once this PR is settled? 🙏

### CODE REVIEW

**Comment by Turbo87** [comment]
released as v0.19.0

**Comment by dcyriller** [comment]
Thank you for taking the time to release this @Turbo87

**Comment by ppcano** [comment]
@dcyriller 

In my own fork, I have upgraded the `emberjs` project to use `blueprint-test-helpers@0.19.1`. But it does not look to be working,  could it be because of the `ember-cli` version of the `emberjs` project?

emberjs/ember.js#17126

**Comment by dcyriller** [comment]
Yes, it is because of ember-cli version in emberjs project. I'm not aware of the best practices regarding peerDependencies. But I guess the package blueprint-test-helper@0.19 would have a peer dependency to ember-cli@3.5

**Comment by ppcano** [comment]
Thank you, commented at emberjs/ember.js#17212

**Pull request merged**
