### PR TITLE
Add AppVeyor manifest

### PR DESCRIPTION
**Pull request by Turbo87**
Let's see if this works...

### CODE REVIEW

**Comment by stefanpenner** [comment]
*waits patiently for appveyor...*

**Comment by Turbo87** [comment]
:trollface:

**Comment by Turbo87** [comment]
Five hours later... still queued

**Comment by stefanpenner** [comment]
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-all"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
 
npm ERR! missing script: test-all
npm ERR! 

``

likely just `npm test`

**Comment by Turbo87** [comment]
whoops... `npm test` obviously makes more sense here

**Comment by Turbo87** [comment]
seems to work fine

**Pull request merged**
