### PR TITLE
Switch to Github Actions

### PR DESCRIPTION
**Pull request by Windvis**
This makes the setup more consistent with the other Ember repos.

I left the .travis.yml file for now since it seems to be used for releases which we will most likely replace with release-plan later.

### CODE REVIEW

**Comment by Windvis** [comment]
It seems Github Actions isn't activated here? I ran it on my own fork and it seems to work as expected: https://github.com/Windvis/ember-cli-blueprint-test-helpers/pull/1

**Comment by Windvis** [comment]
Ah, I didn't know that. I left out that part, but can add it :+1: I wanted to do that in a follow up PR :smile:

**Comment by Windvis** [comment]
@mansona It seems `macos-latest` runs on ARM, which isn't supported by the old node versions we use here. Do I leave that off for now? Did AppVeyor test on macOS?

**Comment by mansona** [comment]
lol I was just writing a reply and you beat me to it 😂 no we never did any mac testing on here so it's safe to remove it 👍

**Comment by Windvis** [comment]
@mansona The linter seems to be failing on Windows: https://github.com/Windvis/ember-cli-blueprint-test-helpers/actions/runs/12253529170/job/34182447934?pr=1 _Something_ seems to be converting the line breaks to `CRLF` on Windows, which causes this rule to fail: https://github.com/ember-cli/ember-cli-blueprint-test-helpers/blob/2916aa07cb578984f4d8519b9968231fee86c8d1/.eslintrc.js#L31

I'm not sure where that conversion happens though. Can I just disable that lint rule? We'll replace it with Prettier soon anyway? Or should I try to find where the conversion happens and see if I can prevent that?

**Comment by mansona** [comment]
just delete that eslint rule, it's silly and it doesn't match what we're doing in other repos these days

**Pull request merged**
