### PR TITLE
Use ESLint for style and code smell checking

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by trabus** [comment]
From slack: 
> Depends on https://github.com/ember-cli/ember-cli/pull/5483 being merged first.

**Comment by Turbo87** [comment]
hmm why do you think the other one needs to be merged first?

**Comment by trabus** [comment]
That was your message from slack, I was just documenting it so I didn't forget.

**Comment by Turbo87** [comment]
ah, that was actually referring to something else :wink: 

This PR shouldn't have any direct dependencies and can be merged before https://github.com/ember-cli/ember-cli/pull/5483

**Comment by trabus** [comment]
Ah, okay. well then. :+1:

**Comment by rwjblue** [comment]
I enabled Travis for this repo, merging now but we should watch for a passing build (and possibly add Travis badge or something)...

**Comment by Turbo87** [comment]
@rwjblue enabling TravisCI requires a `.travis.yml` file though unless you're using Ruby (which is their default).

**Comment by trabus** [comment]
We also need to write tests for the library itself. Currently there aren't any since it's all test helpers.

**Comment by rwjblue** [comment]
:cry:

**Pull request merged**
